### ISSUE TITLE
IDA Capa Explorer - possible infinite loops

### ISSUE THREAD

**Issue by cjchristopher** [mandiant/capa#1330] opened 2023-02-28 05:05 UTC
### Description

I have a number of samples for which capa seems to enter an infinite loop when using Ida as the backend/disassembler.
For reference I provide this hash, which I believe is representative for all the samples I have that cause this behaviour. If required I provide the rest of the samples.

### Steps to Reproduce

Load IDA, load PE file, load Flara capa explorer, start analysis.
Or alternatively, run idat64 providing capa/capa/main.py as a script (modified to a- avoid QPixmap error, and b- dump json report to disk)

**Expected behavior:**

Analysis completes

**Actual behavior:**

Analysis gets stuck on a particular function. Looking at the bottom left corner of IDA gui to watch the address currently being inspected it appears there is an infinite loop, but this is hard to verify specifically.

### Versions

IDA pro 7.6, capa 5.0.0

### Additional Information

Verified on https://www.virustotal.com/gui/file/18ba88ea67c186b15a7b4e5e67acca8895a4e4de3e953a0aa2b574de9b89d9be

**Comment by williballenthin** [comment] 2023-02-28 07:57
thanks for providing the sample binary that causes the issue - i'll try to reproduce and report back here.

**Comment by williballenthin** [comment] 2023-02-28 07:59
> run idat64 providing capa/capa/main.py as a script (modified to a- avoid QPixmap error, and b- dump json report to disk)

are you planning to run capa via IDA programmatically? perhaps we should collaborate to introduce a script that's intended to be used in IDA headless mode.

**Comment by cjchristopher** [comment] 2023-02-28 08:06
I already have run it programmatically, ultimately. I did this by disabling the plugin entirely, and just making a few small modifications to capa/main.py such that I can just pass it to IDA in headless mode with the `-L` flag - the existing method by checking for success via `import idaapi` still works and the rest of the analysis seems to proceed without issue from there.

**Comment by williballenthin** [comment] 2023-02-28 08:12
would you consider contributing this script to the capa repository? then we can direct other users to the script if they want to try the same.

**Comment by williballenthin** [comment] 2023-02-28 10:53
#1332 also reports an infinite loop which I'm triaging right now. maybe these are related. i'll report back when i know more.

**Comment by williballenthin** [comment] 2023-03-23 10:26
closed in https://github.com/mandiant/capa-rules/pull/718

**Closed by williballenthin** 2023-03-23 10:26 UTC
